### ISSUE TITLE
lang-reader-module-paths is undocumented

### ISSUE THREAD

**Issue by lexi-lambda** [AlexKnauth/hygienic-reader-extension#1]
The `lang-reader-module-paths` binding is used in the documentation example, but it is not actually documented anywhere.

**Comment by AlexKnauth** [comment]
I've made a pull request to add it to racket:
https://github.com/racket/racket/pull/1347

That pull request includes this for documentation:
https://github.com/racket/racket/pull/1347/files#diff-b5916053ee085b290ddd80c0c6e8e090R430

But you're right. It's not documented anywhere except there currently.

**Comment by lexi-lambda** [comment]
Ah, gotcha. So it will be moved out of this package once that is merged in, then?

**Comment by AlexKnauth** [comment]
Yes.

**Comment by lexi-lambda** [comment]
Okay, that makes sense then. Thanks for the clarification!
