### ISSUE TITLE
Add MIT License

### ISSUE THREAD

**Issue by AlexKnauth** [AlexKnauth/hygienic-reader-extension#3]
Contributor @SuzanneSoy, I would like to add the MIT License to this repository.

If you agree, please post a message saying so, e.g. — "I hereby license my contributions to `hygienic-reader-extension` under the MIT license."

**Comment by SuzanneSoy** [comment]
I hereby license my contributions to hygienic-reader-extension under the MIT license.

**Comment by AlexKnauth** [comment]
Added in https://github.com/AlexKnauth/hygienic-reader-extension/commit/24a254f3d32875aaab2c9faf9ee84b6a26800479

**Comment by SuzanneSoy** [comment]
If in the future the project's developers want to change the license of this repository to any other (open-source or proprietary, it doesn't matter) or dedicate it to the public domain (e.g. CC0, Unlicense, WTFPL, just writing "Public Domain", …) feel free to do so, I'm happy with that and you do not need to ask me for further confirmation (e.g. if you can't reach me that's not a problem, you can go ahead with the license change).
